//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<orders> orders { get; set; }
    }
}
