//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public string delivery_address { get; set; }
        public Nullable<System.DateTime> estimated_delivery { get; set; }
        public Nullable<System.DateTime> actual_delivery { get; set; }
        public string delivery_status { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
