//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public employees()
        {
            this.service_assignments = new HashSet<service_assignments>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual ICollection<service_assignments> service_assignments { get; set; }
    }
}
