//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPTEntities1 : DbContext
    {
        public OPTEntities1()
            : base("name=OPTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clients> clients { get; set; }
        public DbSet<delivery> delivery { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<order_products> order_products { get; set; }
        public DbSet<order_services> order_services { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<payments> payments { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<service_assignments> service_assignments { get; set; }
        public DbSet<services> services { get; set; }
    }
}
