//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public orders()
        {
            this.delivery = new HashSet<delivery>();
            this.order_products = new HashSet<order_products>();
            this.order_services = new HashSet<order_services>();
            this.payments = new HashSet<payments>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string notes { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual ICollection<delivery> delivery { get; set; }
        public virtual ICollection<order_products> order_products { get; set; }
        public virtual ICollection<order_services> order_services { get; set; }
        public virtual ICollection<payments> payments { get; set; }
    }
}
