//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_services
    {
        public order_services()
        {
            this.service_assignments = new HashSet<service_assignments>();
        }
    
        public int id { get; set; }
        public int order_id { get; set; }
        public int service_id { get; set; }
        public decimal quantity { get; set; }
        public decimal price_at_time { get; set; }
        public string status { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
        public virtual ICollection<service_assignments> service_assignments { get; set; }
    }
}
