//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_products
    {
        public int order_id { get; set; }
        public int product_id { get; set; }
        public decimal quantity { get; set; }
        public decimal price_at_time { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
