//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string payment_method { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
