//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.order_products = new HashSet<order_products>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string unit { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> stock_quantity { get; set; }
    
        public virtual ICollection<order_products> order_products { get; set; }
    }
}
