//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public services()
        {
            this.order_services = new HashSet<order_services>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal base_price { get; set; }
        public string unit { get; set; }
    
        public virtual ICollection<order_services> order_services { get; set; }
    }
}
