//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opt
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_assignments
    {
        public int id { get; set; }
        public int order_service_id { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> assigned_date { get; set; }
        public Nullable<bool> completed { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual order_services order_services { get; set; }
    }
}
